# Generated by Django 4.0.4 on 2023-03-03 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagmentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pdf', models.FileField(upload_to='static/pdf')),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
