# Generated by Django 4.0.4 on 2023-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagmentapp', '0004_alter_book_author_alter_book_bookname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=100),
        ),
    ]
